SEV: mark lanes as optional due to persistent failures (#4872)
Jobs running on the amd-workloads cluster are failing since 2026-03-25
afternoon:

=> https://prow.ci.kubevirt.io/?state=failure&cluster=amd-workloads

Those logs might be related

```
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
```

Signed-off-by: Denis Ollier <dollierp@redhat.com>